"""Page model, parsers, and shared helpers."""

import re
from datetime import date
from pathlib import Path

from .settings import CONFIG

GENERATED_MARKER = "<!-- generated by lint.py: edit above this line only -->"

# Pages allowed to break kebab-case and to have no inbound links.
FILENAME_EXEMPT = ("README.md", "OWNERS.md")

SECRET_PATTERNS = [
    (re.compile(r"(?i)\bpassword\s*[:=]\s*\S"), "password assignment"),
    (re.compile(r"(?i)\bapi[_-]?key\s*[:=]\s*\S"), "api key assignment"),
    (re.compile(r"(?i)\bsecret\s*[:=]\s*\S"), "secret assignment"),
    (re.compile(r"(?i)\btoken\s*[:=]\s*[A-Za-z0-9._-]{8,}"), "token assignment"),
    (re.compile(r"BEGIN (?:RSA |EC |OPENSSH |PGP )?PRIVATE KEY"), "private key block"),
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "AWS access key id"),
    (re.compile(r"(?i)wg[- ]?private"), "wireguard private key reference"),
    (re.compile(r"Bearer\s+[A-Za-z0-9._~+/-]{20,}"), "bearer token"),
]

WIKILINK_RE = re.compile(r"\[\[([^\]\n]+?)\]\]")
KEBAB_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
LOG_HEADER_RE = re.compile(r"^## \[\d{4}-\d{2}-\d{2}\] [a-z][a-z-]*(?: \| .+)?$")
ADR_FILE_RE = re.compile(r"^(\d{4})-[a-z0-9-]+\.md$")
YAML_FENCE_RE = re.compile(r"```yaml\n(.*?)```", re.DOTALL)
KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$")


class Report:
    SEVERITIES = ("ERROR", "WARNING", "INFO")

    def __init__(self):
        self.items = []  # (severity, check, path, message)

    def add(self, severity, check, path, message):
        self.items.append((severity, check, str(path), message))

    def error(self, check, path, message):
        self.add("ERROR", check, path, message)

    def warning(self, check, path, message):
        self.add("WARNING", check, path, message)

    def info(self, check, path, message):
        self.add("INFO", check, path, message)

    def render(self):
        lines = []
        for sev in self.SEVERITIES:
            group = [i for i in self.items if i[0] == sev]
            if not group:
                continue
            lines.append(f"\n{sev}S ({len(group)})")
            for _, check, path, message in sorted(group, key=lambda i: (i[1], i[2])):
                lines.append(f"  [{check}] {path}: {message}")
        counts = {s: sum(1 for i in self.items if i[0] == s) for s in self.SEVERITIES}
        lines.append(
            f"\nsummary: {counts['ERROR']} errors, "
            f"{counts['WARNING']} warnings, {counts['INFO']} info"
        )
        return "\n".join(lines)

    @property
    def has_errors(self):
        return any(i[0] == "ERROR" for i in self.items)


def unquote(value):
    return value.strip().strip("'\"")


def as_list(value):
    """Normalize a frontmatter field to a list ([] for missing/None)."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return value


def parse_frontmatter(text):
    """Minimal YAML frontmatter parser: flat keys, inline and block lists.

    Returns (fields, error). Nested mappings beyond one list level are not
    supported by design; the page schemas only use flat fields.
    """
    if not text.startswith("---"):
        return None, "missing frontmatter"
    lines = text.split("\n")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return None, "unterminated frontmatter"
    fields = {}
    current_list_key = None
    for line in lines[1:end]:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith((" ", "\t")):
            m = KEY_RE.match(line)
            if not m:
                return None, f"unparseable frontmatter line: {stripped!r}"
            key, raw_val = m.group(1), m.group(2).strip()
            current_list_key = None
            if raw_val == "":
                fields[key] = []
                current_list_key = key
            elif raw_val.startswith("[") and raw_val.endswith("]"):
                inner = raw_val[1:-1].strip()
                fields[key] = (
                    [unquote(v) for v in inner.split(",") if v.strip()]
                    if inner else []
                )
            else:
                fields[key] = unquote(raw_val)
        elif stripped.startswith("- ") and current_list_key is not None:
            fields[current_list_key].append(unquote(stripped[2:]))
        # Indented non-list lines (nested mappings) are tolerated but ignored.
    return fields, None


def parse_iso_date(value):
    try:
        return date.fromisoformat(str(value))
    except (ValueError, TypeError):
        return None


def strip_code_blocks(body):
    """Blank fenced code blocks (preserving line count) so wikilinks and
    mention hints inside examples don't count but line numbers stay right."""
    return re.sub(
        r"```.*?```",
        lambda m: "\n" * m.group(0).count("\n"),
        body,
        flags=re.DOTALL,
    )


def line_at(text, offset):
    """1-based line number of a character offset."""
    return text[:offset].count("\n") + 1


class Page:
    def __init__(self, path, root):
        self.path = path
        self.rel = path.relative_to(root).as_posix()
        self.text = path.read_text(encoding="utf-8", errors="replace")
        self.fields, self.fm_error = parse_frontmatter(self.text)
        self.body = self._body_text()
        self.prose = strip_code_blocks(self.text)       # full text, file-accurate lines
        self.body_prose = strip_code_blocks(self.body)  # body only, for content checks

    def _body_text(self):
        # Mirror parse_frontmatter's delimiter handling (strip before compare)
        # so a closing "--- " with trailing whitespace still yields the body.
        if not self.text.startswith("---"):
            return self.text
        lines = self.text.split("\n")
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return "\n".join(lines[i + 1:])
        return ""

    @property
    def stem(self):
        return self.path.stem

    @property
    def rel_no_ext(self):
        return self.rel[:-3] if self.rel.endswith(".md") else self.rel

    @property
    def type(self):
        return (self.fields or {}).get("type")

    def field_list(self, name):
        return as_list((self.fields or {}).get(name))


def discover_pages(root, report):
    pages = []
    for d in CONFIG["page_dirs"]:
        dir_path = root / d
        if not dir_path.is_dir():
            continue
        for path in sorted(dir_path.rglob("*.md")):
            pages.append(Page(path, root))
    known = set(CONFIG["page_dirs"]) | set(CONFIG["non_page_allowed"])
    for entry in sorted(root.iterdir()):
        if entry.name not in known and not entry.name.startswith("."):
            report.warning(
                "layout", entry.name,
                "unknown top-level entry; the schema says ask before inventing folders",
            )
    return pages


def build_link_index(pages):
    """stem -> [pages] and rel/rel_no_ext -> page for link resolution."""
    by_stem = {}
    by_rel = {}
    for p in pages:
        by_stem.setdefault(p.stem, []).append(p)
        by_rel[p.rel_no_ext] = p
        by_rel[p.rel] = p
    return by_stem, by_rel


def resolve_link(target, by_stem, by_rel):
    target = target.split("|")[0].split("#")[0].strip()
    if not target:
        return None
    if target in by_rel:
        return by_rel[target]
    stem = target[:-3] if target.endswith(".md") else target
    candidates = by_stem.get(stem.split("/")[-1], [])
    if "/" in target:
        matches = [p for p in candidates if p.rel_no_ext.endswith(stem)]
        return matches[0] if len(matches) == 1 else None
    return candidates[0] if len(candidates) == 1 else None


def _pinning_fence(text):
    """The yaml fence holding the pinning data: searched only above the
    generated marker, and required to carry a pinning key, so example yaml
    blocks elsewhere in the file can never displace it."""
    if GENERATED_MARKER in text:
        text = text.split(GENERATED_MARKER)[0]
    for m in YAML_FENCE_RE.finditer(text):
        if re.search(r"^(repo|last_synced_commit):", m.group(1), re.MULTILINE):
            return m.group(1)
    return None


def parse_index_pinning(root):
    """Parse the yaml pinning block at the top of index.md, if any.
    Handles quoted scalars and both inline and block-style nested lists."""
    index = root / "index.md"
    if not index.is_file():
        return {}
    block = _pinning_fence(index.read_text(encoding="utf-8", errors="replace"))
    if block is None:
        return {}
    pinning = {}
    current_map = None   # top-level key holding a nested mapping
    current_list = None  # (map key, nested key) of a block list being filled
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith((" ", "\t")):
            m = KEY_RE.match(line)
            if not m:
                continue
            key, val = m.group(1), m.group(2).strip()
            current_list = None
            if val == "":
                pinning[key] = {}
                current_map = key
            else:
                pinning[key] = unquote(val)
                current_map = None
        elif stripped.startswith("- ") and current_list is not None:
            map_key, key = current_list
            pinning[map_key][key].append(unquote(stripped[2:]))
        elif current_map is not None:
            m = KEY_RE.match(stripped)
            if not m:
                continue
            key, val = m.group(1), m.group(2).strip()
            if val.startswith("[") and val.endswith("]"):
                inner = val[1:-1].strip()
                pinning[current_map][key] = (
                    [unquote(v) for v in inner.split(",") if v.strip()]
                    if inner else []
                )
                current_list = None
            elif val == "":
                pinning[current_map][key] = []
                current_list = (current_map, key)
            else:
                pinning[current_map][key] = unquote(val)
                current_list = None
    return pinning
