"""Page model, parsers, and shared helpers."""

import re
from datetime import date
from fnmatch import fnmatch
from pathlib import Path, PurePosixPath

from .settings import CONFIG

GENERATED_MARKER = "<!-- generated by lint.py: edit above this line only -->"

# OKF (Open Knowledge Format) version this engine produces and validates.
OKF_VERSION = "0.1"

# Pages allowed to break kebab-case and to have no inbound links.
FILENAME_EXEMPT = ("README.md", "OWNERS.md")

SECRET_PATTERNS = [
    (re.compile(r"(?i)\bpassword\s*[:=]\s*\S"), "password assignment"),
    (re.compile(r"(?i)\bapi[_-]?key\s*[:=]\s*\S"), "api key assignment"),
    (re.compile(r"(?i)\bsecret\s*[:=]\s*\S"), "secret assignment"),
    (re.compile(r"(?i)\btoken\s*[:=]\s*[A-Za-z0-9._-]{8,}"), "token assignment"),
    (re.compile(r"BEGIN (?:RSA |EC |OPENSSH |PGP )?PRIVATE KEY"), "private key block"),
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "AWS access key id"),
    (re.compile(r"(?i)wg[- ]?private"), "wireguard private key reference"),
    (re.compile(r"Bearer\s+[A-Za-z0-9._~+/-]{20,}"), "bearer token"),
]

# [text](target) markdown links, excluding images; target is group 1. An
# optional "title" after the target is tolerated. Images are blanked first
# (blank_images) so an image wrapped in a link exposes the link's target.
MD_LINK_RE = re.compile(r"(?<!\!)\[[^\]\n]*\]\(([^)\s]+)(?:\s+\"[^\"\n]*\")?\)")
# ![alt](src) image links, blanked before markdown-link scanning.
IMAGE_MD_RE = re.compile(r"!\[[^\]\n]*\]\([^)\n]*\)")
# Inline code spans: a run of N backticks, content, then N backticks. Matching
# the run length blanks double-backtick spans (``...``), not just single ones.
INLINE_CODE_RE = re.compile(r"(`+)[^\n]*?\1")
KEBAB_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
# OKF log format: one "## YYYY-MM-DD" heading per date (newest first), each
# entry a bullet opening with a bold action word: "- **Update**: ...".
LOG_DATE_HEADER_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2})$")
LOG_ENTRY_RE = re.compile(r"^- \*\*[A-Z][A-Za-z-]*\*\*: .+$")
ADR_FILE_RE = re.compile(r"^(\d{4})-[a-z0-9-]+\.md$")
YAML_FENCE_RE = re.compile(r"```yaml\n(.*?)```", re.DOTALL)
KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$")


class Report:
    SEVERITIES = ("ERROR", "WARNING", "INFO")

    def __init__(self):
        self.items = []  # (severity, check, path, message)

    def add(self, severity, check, path, message):
        self.items.append((severity, check, str(path), message))

    def error(self, check, path, message):
        self.add("ERROR", check, path, message)

    def warning(self, check, path, message):
        self.add("WARNING", check, path, message)

    def info(self, check, path, message):
        self.add("INFO", check, path, message)

    def render(self):
        lines = []
        for sev in self.SEVERITIES:
            group = [i for i in self.items if i[0] == sev]
            if not group:
                continue
            lines.append(f"\n{sev}S ({len(group)})")
            for _, check, path, message in sorted(group, key=lambda i: (i[1], i[2])):
                lines.append(f"  [{check}] {path}: {message}")
        counts = {s: sum(1 for i in self.items if i[0] == s) for s in self.SEVERITIES}
        lines.append(
            f"\nsummary: {counts['ERROR']} errors, "
            f"{counts['WARNING']} warnings, {counts['INFO']} info"
        )
        return "\n".join(lines)

    @property
    def has_errors(self):
        return any(i[0] == "ERROR" for i in self.items)


def unquote(value):
    return value.strip().strip("'\"")


def as_list(value):
    """Normalize a frontmatter field to a list ([] for missing/None)."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return value


def parse_frontmatter(text):
    """Minimal YAML frontmatter parser: flat keys, inline and block lists.

    Returns (fields, error). Nested mappings beyond one list level are not
    supported by design; the page schemas only use flat fields.
    """
    if not text.startswith("---"):
        return None, "missing frontmatter"
    lines = text.split("\n")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return None, "unterminated frontmatter"
    fields = {}
    current_list_key = None
    for line in lines[1:end]:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith((" ", "\t")):
            m = KEY_RE.match(line)
            if not m:
                return None, f"unparseable frontmatter line: {stripped!r}"
            key, raw_val = m.group(1), m.group(2).strip()
            current_list_key = None
            if raw_val == "":
                fields[key] = []
                current_list_key = key
            elif raw_val.startswith("[") and raw_val.endswith("]"):
                inner = raw_val[1:-1].strip()
                fields[key] = (
                    [unquote(v) for v in inner.split(",") if v.strip()]
                    if inner else []
                )
            else:
                fields[key] = unquote(raw_val)
        elif stripped.startswith("- ") and current_list_key is not None:
            fields[current_list_key].append(unquote(stripped[2:]))
        # Indented non-list lines (nested mappings) are tolerated but ignored.
    return fields, None


def parse_iso_date(value):
    try:
        return date.fromisoformat(str(value))
    except (ValueError, TypeError):
        return None


def strip_code_blocks(body):
    """Blank fenced code blocks (preserving line count) so wikilinks and
    mention hints inside examples don't count but line numbers stay right."""
    return re.sub(
        r"```.*?```",
        lambda m: "\n" * m.group(0).count("\n"),
        body,
        flags=re.DOTALL,
    )


def _blank(match):
    """Replace a match with spaces of equal length, preserving newlines so
    character offsets and line numbers stay accurate."""
    return "".join("\n" if c == "\n" else " " for c in match.group(0))


def blank_inline_code(text):
    """Blank `inline code` spans (length- and line-preserving) so link-shaped
    text inside them is not treated as a wiki or markdown link. Handles
    multi-backtick spans."""
    return INLINE_CODE_RE.sub(_blank, text)


def blank_images(text):
    """Blank ![alt](src) image links so they are not mistaken for markdown
    page links, and so an image wrapped in a link exposes the outer target."""
    return IMAGE_MD_RE.sub(_blank, text)


def blank_frontmatter(text):
    """Blank the leading YAML frontmatter block (line-preserving) so body
    scanners see only body content while keeping file-accurate line numbers."""
    if not text.startswith("---"):
        return text
    lines = text.split("\n")
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join([""] * (i + 1) + lines[i + 1:])
    return text


def line_at(text, offset):
    """1-based line number of a character offset."""
    return text[:offset].count("\n") + 1


class Page:
    def __init__(self, path, root):
        self.path = path
        self.rel = path.relative_to(root).as_posix()
        self.text = path.read_text(encoding="utf-8", errors="replace")
        self.fields, self.fm_error = parse_frontmatter(self.text)
        self.body = self._body_text()
        # Code (fenced and inline) is blanked length-preservingly so link and
        # mention scanners ignore it uniformly while line numbers stay accurate.
        self.prose = blank_inline_code(strip_code_blocks(self.text))
        self.body_prose = blank_inline_code(strip_code_blocks(self.body))

    def _body_text(self):
        # Mirror parse_frontmatter's delimiter handling (strip before compare)
        # so a closing "--- " with trailing whitespace still yields the body.
        if not self.text.startswith("---"):
            return self.text
        lines = self.text.split("\n")
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return "\n".join(lines[i + 1:])
        return ""

    @property
    def stem(self):
        return self.path.stem

    @property
    def rel_no_ext(self):
        return self.rel[:-3] if self.rel.endswith(".md") else self.rel

    @property
    def type(self):
        return (self.fields or {}).get("type")

    def field_list(self, name):
        return as_list((self.fields or {}).get(name))


def discover_pages(root, report):
    # Normalize through PurePosixPath so "./x" and "x" compare equal to the
    # path pathlib actually writes/reads for the index.
    index_file = CONFIG["index_file"]
    index_rel = PurePosixPath(index_file).as_posix() if index_file else None
    pages = []
    for d in CONFIG["page_dirs"]:
        dir_path = root / d
        if not dir_path.is_dir():
            continue
        for path in sorted(dir_path.rglob("*.md")):
            # The generated index is a derived artifact, not a page, even
            # when index_file places it inside a page dir.
            if index_rel is not None and path.relative_to(root).as_posix() == index_rel:
                continue
            pages.append(Page(path, root))
    # non_page_allowed entries are fnmatch patterns; exact names still match.
    # The generated index and the log are engine artifacts, so allow whichever
    # top-level entry they live under even when relocated.
    known = list(CONFIG["page_dirs"]) + list(CONFIG["non_page_allowed"])
    for artifact in (CONFIG["index_file"], CONFIG["log_file"]):
        if artifact:
            known.append(PurePosixPath(artifact).parts[0])
    for entry in sorted(root.iterdir()):
        name = entry.name
        if name.startswith("."):
            continue
        if any(fnmatch(name, pattern) for pattern in known):
            continue
        report.warning(
            "layout", name,
            "unknown top-level entry; the schema says ask before inventing folders",
        )
    return pages


def discover_okf_bundle(root):
    """Every markdown file the OKF conformance rules apply to: the whole tree
    minus dot-directories, the human-owned raw/ sources (a deliberate,
    documented deviation; prime directive 1 forbids editing them), and the
    reserved index/log files (which have their own structural rules)."""
    reserved = {CONFIG["index_file"], CONFIG["log_file"]}
    raw = CONFIG["raw_dir"]
    files = []
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(root).as_posix()
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        if raw and (rel == raw or rel.startswith(raw + "/")):
            continue
        if rel in reserved:
            continue
        files.append(path)
    return files


def build_link_index(pages):
    """stem -> [pages] and rel/rel_no_ext -> page for link resolution."""
    by_stem = {}
    by_rel = {}
    for p in pages:
        by_stem.setdefault(p.stem, []).append(p)
        by_rel[p.rel_no_ext] = p
        by_rel[p.rel] = p
    return by_stem, by_rel


def resolve_link(target, by_stem, by_rel):
    target = target.split("|")[0].split("#")[0].strip()
    if not target:
        return None
    if target in by_rel:
        return by_rel[target]
    stem = target[:-3] if target.endswith(".md") else target
    candidates = by_stem.get(stem.split("/")[-1], [])
    if "/" in target:
        matches = [p for p in candidates if p.rel_no_ext.endswith(stem)]
        return matches[0] if len(matches) == 1 else None
    return candidates[0] if len(candidates) == 1 else None


def _pinning_fence(text):
    """The yaml fence holding the pinning data: searched only above the
    generated marker, and required to carry a pinning key, so example yaml
    blocks elsewhere in the file can never displace it."""
    if GENERATED_MARKER in text:
        text = text.split(GENERATED_MARKER)[0]
    for m in YAML_FENCE_RE.finditer(text):
        if re.search(r"^(repo|last_synced_commit):", m.group(1), re.MULTILINE):
            return m.group(1)
    return None


def parse_index_pinning(root):
    """Parse the yaml pinning block at the top of the index, if any.
    Handles quoted scalars and both inline and block-style nested lists."""
    if CONFIG["index_file"] is None:
        return {}
    index = root / CONFIG["index_file"]
    if not index.is_file():
        return {}
    block = _pinning_fence(index.read_text(encoding="utf-8", errors="replace"))
    if block is None:
        return {}
    pinning = {}
    current_map = None   # top-level key holding a nested mapping
    current_list = None  # (map key, nested key) of a block list being filled
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith((" ", "\t")):
            m = KEY_RE.match(line)
            if not m:
                continue
            key, val = m.group(1), m.group(2).strip()
            current_list = None
            if val == "":
                pinning[key] = {}
                current_map = key
            else:
                pinning[key] = unquote(val)
                current_map = None
        elif stripped.startswith("- ") and current_list is not None:
            map_key, key = current_list
            pinning[map_key][key].append(unquote(stripped[2:]))
        elif current_map is not None:
            m = KEY_RE.match(stripped)
            if not m:
                continue
            key, val = m.group(1), m.group(2).strip()
            if val.startswith("[") and val.endswith("]"):
                inner = val[1:-1].strip()
                pinning[current_map][key] = (
                    [unquote(v) for v in inner.split(",") if v.strip()]
                    if inner else []
                )
                current_list = None
            elif val == "":
                pinning[current_map][key] = []
                current_list = (current_map, key)
            else:
                pinning[current_map][key] = unquote(val)
                current_list = None
    return pinning
